config/routes.rb
Rails.application.routes.draw do
  resource :home
  get '/index', to: 'home#index'
  match '/csv', to: 'home#process_csv', via: [:get, :post]

  root to: 'home#process_csv'

  namespace :api do
  	namespace :v1 do
  		resources :question_apis, except: [:new, :edit, :index]
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mapping.rb
class Mapping < ApplicationRecord
	has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  default_scope { order(:id) }
  
  belongs_to :mapping
  belongs_to :role

  def as_json(*)
    {
      id: id,
      appears: appears,
      conditions: conditions,
      frequency: frequency,
      mapping: mapping.name,
      priority: priority,
      que_text: que_text,
      que_type: que_type,
      required: required.to_s.titleize,
      role: role.name,
      teaming_stages: teaming_stages
    }   
  end
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :questions
end

app/controllers/api/v1/question_apis_controller.rb
class Api::V1::QuestionApisController < ApplicationController
  before_action :get_resource, except: [:create]
  
  def create
    
  end

  def show
    
  end

  def update
    @question.update(update_params)
    render json: {question: @question}
  end

  def destroy
    @question.destroy
    render json: {id: @question.id}
  end

  private
  def update_params
    params.require(:question).permit(:appears, :conditions, :frequency, :priority, :que_text, :que_type, :required, :teaming_stages)
  end

  def get_resource
    @question = Question.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.includes(:mapping, :role).paginate(page: params[:page], per_page: 10)
  end

  def process_csv
    if request.post?
      begin
        ::CsvProcessor::Processor.new(params.require(:questions_csv)).process
      rescue => e
        flash[:alert] = "Failed: #{e.message}"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= react_component("QuestionsIndex", { questions: @questions.as_json }) %>
<%= will_paginate @questions %>

app/views/home/process_csv.html.erb
<div class="col-6 card m-auto top-40">
  <div class="card-body text-center">
    <h3>Upload CSV</h3>
    <%= form_tag csv_path, multipart: true do%>
      <div class="form-group">
        <%= file_field_tag 'questions_csv', class: 'p-2 file-border' %>     
      </div>
      <%= button_tag 'Upload', class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

<style>
  .top-40 {
    top: 40px;
  }
  .file-border {
    border: 1px solid black;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnaghaTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'javascript', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="col-md-12 mt-4">
      <div class="text-center mt-4">
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
      <div class="text-right m-4">
        <%= link_to 'CSV Upload', csv_path, class: 'btn btn-info' %>
        <%= link_to 'Questions', index_path, class: 'btn btn-info' %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>